spring:
  main:
    banner-mode: "off"
book.file.name: "testBDJSON.json"
test:
  url:
    books:
      list:
        right: "http://localhost:8080/books/list"
        wrong: "http://localhost:8080/books/"
